apiVersion: v1
kind: Service
metadata:
  name: abcproject-service
  annotations: {}
spec:
  type: NodePort
  selector:
    app: abc-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30888

