---
- name: Deploy ABC Project to Kubernetes
  hosts: localhost
  connection: local
  tasks:
    - name: Delete existing Kubernetes deployment (if any)
      ansible.builtin.command: kubectl delete deployment abc-deployment --ignore-not-found
      ignore_errors: true

    - name: Delete existing Kubernetes service (if any)
      ansible.builtin.command: kubectl delete service abcproject-service --ignore-not-found
      ignore_errors: true

    - name: Apply Kubernetes deployment
      ansible.builtin.command: kubectl apply -f {{ playbook_dir }}/../k8s/deployment.yaml

    - name: Apply Kubernetes service
      ansible.builtin.command: kubectl apply -f {{ playbook_dir }}/../k8s/service.yaml

    - name: Wait for port-forward to be active on port 8088
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: 8088
        delay: 5
        timeout: 30

